In [23]:
import pandas as pd
import RiotAnalyzer as Ra
import ProFinder as pf
import json as js
import ast
import time
api_key, api_key_time = None, 0

In [24]:
from tkinter import *

In [25]:
if not api_key:
    print("Get a developer API key from https://developer.riotgames.com/")
    api_key = input("Enter API key: ")
    
    api_key_time = time.time()
time_elapsed = time.time() - api_key_time
# Format time_elapsed to x Hours y minutes z seconds
time_elapsed = time.strftime("%H hours, %M minutes, and %S seconds ago", time.gmtime(time_elapsed))

print(f"Current api key: {api_key},\nretrieved {time_elapsed}")

Current api key: 'Insert API',
retrieved 13 hours, 18 minutes, and 01 seconds ago

In [26]:
tokens = [api_key]
version = "13.17.1"
ra = Ra.RiotAnalyzer(tokens, region="NA", version=version)

In [40]:
df1 = pd.read_csv("pro_df.csv")
df1

,Region,Team,Official Summoner Name,ids,Roles (LeaguePedia),Roles (RCD)
0,BR,FLUXO,Baldan,{},Top,NaN
1,BR,FLUXO,Forlin,{},Top,NaN
2,BR,FLUXO,Tay,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303...",Top,NaN
3,BR,FLUXO,Disamis,{},Jungle,NaN
4,BR,FLUXO,Ancrath,{},Jungle,NaN
...,...,...,...,...,...,...
1193,VN,NaN,Emo,{},Mid,Sub/Mid
1194,VN,NaN,Nugu,"{'VN': '211221', 'KR': '우주를 줄게 1802'}",Mid,Mid
1195,VN,NaN,Slowz,{},Top,Bot
1196,VN,NaN,Zodiac,{'VN': ['Zodiac12']},Sup,Sup
1197,VN,NaN,Ryuk,{},Top,Sub/Top

In [74]:
df = pd.read_csv("pro_df.csv")
all_accounts = []
pro_accounts_dict = {}
# Loops through all rows and gets dictionary
for num in range(len(df.get('ids'))):
    home_reigon = str(df.get('Region')[num]) + ":"
    main_name = df.get('Official Summoner Name')[num]
    a = ast.literal_eval(df.get('ids')[num])
    # we add the main account to the list of alt accounts
    if home_reigon not in (list(a.keys())):
        a[home_reigon] = [main_name]
    else:
        a[home_reigon].append(main_name)
    all_accounts.append(a)
#Adds all accounts to the new dataframe
df['Account_list'] = all_accounts
df.get('Account_li  st')[12]
df

,Region,Team,Official Summoner Name,ids,Roles (LeaguePedia),Roles (RCD),Account_list
0,BR,FLUXO,Baldan,{},Top,NaN,{'BR:': ['Baldan']}
1,BR,FLUXO,Forlin,{},Top,NaN,{'BR:': ['Forlin']}
2,BR,FLUXO,Tay,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303...",Top,NaN,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303..."
3,BR,FLUXO,Disamis,{},Jungle,NaN,{'BR:': ['Disamis']}
4,BR,FLUXO,Ancrath,{},Jungle,NaN,{'BR:': ['Ancrath']}
...,...,...,...,...,...,...,...
1193,VN,NaN,Emo,{},Mid,Sub/Mid,{'VN:': ['Emo']}
1194,VN,NaN,Nugu,"{'VN': '211221', 'KR': '우주를 줄게 1802'}",Mid,Mid,"{'VN': '211221', 'KR': '우주를 줄게 1802', 'VN:': [..."
1195,VN,NaN,Slowz,{},Top,Bot,{'VN:': ['Slowz']}
1196,VN,NaN,Zodiac,{'VN': ['Zodiac12']},Sup,Sup,"{'VN': ['Zodiac12'], 'VN:': ['Zodiac']}"
1197,VN,NaN,Ryuk,{},Top,Sub/Top,{'VN:': ['Ryuk']}

In [68]:
ts = ra.get_mastery_by_summoner_name("LostRoss", "NA")
ts

,championName,championLevel,championPoints,lastPlayTime,lastPlayDate,percent
Rank,,,,,,
1,Neeko,7,130678,Jul 08 09:18,2023-07-08 09:18:03,19.40%
2,Ezreal,5,51703,Aug 02 12:11,2023-08-02 12:11:14,7.67%
3,Ashe,5,48314,Jul 14 10:24,2023-07-14 10:24:38,7.17%
4,Swain,6,44314,Feb 21 23:39,2023-02-21 23:39:15,6.58%
5,Seraphine,5,33838,Jun 08 02:32,2023-06-08 02:32:44,5.02%
...,...,...,...,...,...,...
102,Camille,1,123,Mar 05 07:22,2021-03-05 07:22:59,0.02%
103,Vel'Koz,1,121,May 18 00:16,2022-05-18 00:16:32,0.02%
104,Gangplank,1,115,Mar 31 21:42,2022-03-31 21:42:01,0.02%
105,Orianna,1,101,Nov 07 23:02,2021-11-07 23:02:05,0.01%
106,Yorick,1,80,Mar 31 23:55,2022-03-31 23:55:24,0.01%

In [99]:
champ_df = pd.read_excel("Champs_w_roles.xlsx")
champ_df

,version,id,key,name,title,blurb,info,image,tags,partype,stats,Top,Jungle,Mid,Bot,Sup
0,13.17.1,Aatrox,266,Aatrox,the Darkin Blade,Once honored defenders of Shurima against the ...,"{'attack': 8, 'defense': 4, 'magic': 3, 'diffi...","{'full': 'Aatrox.png', 'sprite': 'champion0.pn...","['Fighter', 'Tank']",Blood Well,"{'hp': 650, 'hpperlevel': 114, 'mp': 0, 'mpper...",True,NaN,NaN,NaN,NaN
1,13.17.1,Ahri,103,Ahri,the Nine-Tailed Fox,Innately connected to the magic of the spirit ...,"{'attack': 3, 'defense': 4, 'magic': 8, 'diffi...","{'full': 'Ahri.png', 'sprite': 'champion0.png'...","['Mage', 'Assassin']",Mana,"{'hp': 590, 'hpperlevel': 96, 'mp': 418, 'mppe...",NaN,NaN,true,NaN,NaN
2,13.17.1,Akali,84,Akali,the Rogue Assassin,Abandoning the Kinkou Order and her title of t...,"{'attack': 5, 'defense': 3, 'magic': 8, 'diffi...","{'full': 'Akali.png', 'sprite': 'champion0.png...",['Assassin'],Energy,"{'hp': 570, 'hpperlevel': 119, 'mp': 200, 'mpp...",True,NaN,true,NaN,NaN
3,13.17.1,Akshan,166,Akshan,the Rogue Sentinel,"Raising an eyebrow in the face of danger, Aksh...","{'attack': 0, 'defense': 0, 'magic': 0, 'diffi...","{'full': 'Akshan.png', 'sprite': 'champion0.pn...","['Marksman', 'Assassin']",Mana,"{'hp': 630, 'hpperlevel': 107, 'mp': 350, 'mpp...",NaN,NaN,true,NaN,NaN
4,13.17.1,Alistar,12,Alistar,the Minotaur,Always a mighty warrior with a fearsome reputa...,"{'attack': 6, 'defense': 9, 'magic': 5, 'diffi...","{'full': 'Alistar.png', 'sprite': 'champion0.p...","['Tank', 'Support']",Mana,"{'hp': 685, 'hpperlevel': 120, 'mp': 350, 'mpp...",NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,13.17.1,Zeri,221,Zeri,The Spark of Zaun,"A headstrong, spirited young woman from Zaun's...","{'attack': 8, 'defense': 5, 'magic': 3, 'diffi...","{'full': 'Zeri.png', 'sprite': 'champion5.png'...",['Marksman'],Mana,"{'hp': 630, 'hpperlevel': 110, 'mp': 250, 'mpp...",NaN,NaN,NaN,True,NaN
160,13.17.1,Ziggs,115,Ziggs,the Hexplosives Expert,"With a love of big bombs and short fuses, the ...","{'attack': 2, 'defense': 4, 'magic': 9, 'diffi...","{'full': 'Ziggs.png', 'sprite': 'champion5.png...",['Mage'],Mana,"{'hp': 606, 'hpperlevel': 106, 'mp': 480, 'mpp...",NaN,NaN,true,True,NaN
161,13.17.1,Zilean,26,Zilean,the Chronokeeper,"Once a powerful Icathian mage, Zilean became o...","{'attack': 2, 'defense': 5, 'magic': 8, 'diffi...","{'full': 'Zilean.png', 'sprite': 'champion5.pn...","['Support', 'Mage']",Mana,"{'hp': 574, 'hpperlevel': 96, 'mp': 452, 'mppe...",NaN,NaN,NaN,True,NaN
162,13.17.1,Zoe,142,Zoe,the Aspect of Twilight,"As the embodiment of mischief, imagination, an...","{'attack': 1, 'defense': 7, 'magic': 8, 'diffi...","{'full': 'Zoe.png', 'sprite': 'champion5.png',...","['Mage', 'Support']",Mana,"{'hp': 630, 'hpperlevel': 106, 'mp': 425, 'mpp...",NaN,NaN,true,NaN,NaN
163,13.17.1,Zyra,143,Zyra,Rise of the Thorns,"Born in an ancient, sorcerous catastrophe, Zyr...","{'attack': 4, 'defense': 3, 'magic': 8, 'diffi...","{'full': 'Zyra.png', 'sprite': 'champion5.png'...","['Mage', 'Support']",Mana,"{'hp': 574, 'hpperlevel': 93, 'mp': 418, 'mppe...",NaN,NaN,NaN,NaN,True

In [121]:
#Creates a dictionary which contains the roles of all champions
champ_role_dict = {}
champ_df = pd.read_excel("Champs_w_roles.xlsx")
role_list = ['Top', 'Jungle', 'Mid', 'Bot', 'Sup']
for num in range(len(champ_df.get('name'))):
    champ_name = champ_df.get('name')[num]
    #cycles through all roles and adds to dictionary if the champ plays that role
    for role in role_list:
        if type(champ_df.get(role)[num]) != float:
            if champ_name not in champ_role_dict:
                champ_role_dict[champ_name] = [role]
            else:
                champ_role_dict[champ_name].append(role)
champ_role_dict

{'Aatrox': ['Top'],
 'Ahri': ['Mid'],
 'Akali': ['Top', 'Mid'],
 'Akshan': ['Mid'],
 'Alistar': ['Sup'],
 'Amumu': ['Jungle', 'Sup'],
 'Anivia': ['Mid'],
 'Annie': ['Mid', 'Sup'],
 'Aphelios': ['Bot'],
 'Ashe': ['Bot'],
 'Aurelion Sol': ['Mid'],
 'Azir': ['Mid'],
 'Bard': ['Sup'],
 "Bel'Veth": ['Jungle'],
 'Blitzcrank': ['Sup'],
 'Brand': ['Mid', 'Sup'],
 'Braum': ['Sup'],
 'Caitlyn': ['Bot'],
 'Camille': ['Top'],
 'Cassiopeia': ['Top', 'Mid'],
 "Cho'Gath": ['Top', 'Mid'],
 'Corki': ['Mid'],
 'Darius': ['Top'],
 'Diana': ['Jungle', 'Mid'],
 'Draven': ['Bot'],
 'Dr. Mundo': ['Top'],
 'Ekko': ['Jungle', 'Mid'],
 'Elise': ['Jungle'],
 'Evelynn': ['Jungle'],
 'Ezreal': ['Bot'],
 'Fiddlesticks': ['Jungle'],
 'Fiora': ['Top'],
 'Fizz': ['Mid'],
 'Galio': ['Mid', 'Sup'],
 'Gangplank': ['Top'],
 'Garen': ['Top'],
 'Gnar': ['Top'],
 'Gragas': ['Top', 'Jungle'],
 'Graves': ['Jungle'],
 'Gwen': ['Top'],
 'Hecarim': ['Jungle'],
 'Heimerdinger': ['Top', 'Sup'],
 'Illaoi': ['Top'],
 'Irelia': ['Top', 'Mid'],
 'Ivern': ['Jungle'],
 'Janna': ['Sup'],
 'Jarvan IV': ['Jungle'],
 'Jax': ['Top'],
 'Jayce': ['Top', 'Mid'],
 'Jhin': ['Bot'],
 'Jinx': ['Bot'],
 "Kai'Sa": ['Bot'],
 'Kalista': ['Bot'],
 'Karma': ['Sup'],
 'Karthus': ['Jungle', 'Bot'],
 'Kassadin': ['Mid'],
 'Katarina': ['Mid'],
 'Kayle': ['Top'],
 'Kayn': ['Jungle'],
 'Kennen': ['Top'],
 "Kha'Zix": ['Jungle'],
 'Kindred': ['Jungle'],
 'Kled': ['Top'],
 "Kog'Maw": ['Bot'],
 "K'Sante": ['Top'],
 'LeBlanc': ['Mid'],
 'Lee Sin': ['Jungle'],
 'Leona': ['Sup'],
 'Lillia': ['Jungle'],
 'Lissandra': ['Mid'],
 'Lucian': ['Bot'],
 'Lulu': ['Sup'],
 'Lux': ['Mid', 'Sup'],
 'Malphite': ['Top'],
 'Malzahar': ['Mid'],
 'Maokai': ['Jungle', 'Sup'],
 'Master Yi': ['Jungle'],
 'Milio': ['Sup'],
 'Miss Fortune': ['Bot'],
 'Wukong': ['Top', 'Jungle'],
 'Mordekaiser': ['Top'],
 'Morgana': ['Sup'],
 'Naafiri': ['Top', 'Mid'],
 'Nami': ['Sup'],
 'Nasus': ['Top'],
 'Nautilus': ['Sup'],
 'Neeko': ['Mid', 'Sup'],
 'Nidalee': ['Jungle'],
 'Nilah': ['Bot'],
 'Nocturne': ['Jungle'],
 'Nunu & Willump': ['Jungle'],
 'Olaf': ['Top'],
 'Orianna': ['Mid'],
 'Ornn': ['Top'],
 'Pantheon': ['Top', 'Mid'],
 'Poppy': ['Top', 'Jungle'],
 'Pyke': ['Sup'],
 'Qiyana': ['Mid'],
 'Quinn': ['Top'],
 'Rakan': ['Sup'],
 'Rammus': ['Jungle'],
 "Rek'Sai": ['Jungle'],
 'Rell': ['Sup'],
 'Renata Glasc': ['Sup'],
 'Renekton': ['Top'],
 'Rengar': ['Top', 'Jungle'],
 'Riven': ['Top'],
 'Rumble': ['Top', 'Mid'],
 'Ryze': ['Top', 'Mid'],
 'Samira': ['Bot'],
 'Sejuani': ['Jungle'],
 'Senna': ['Sup'],
 'Seraphine': ['Bot', 'Sup'],
 'Sett': ['Top'],
 'Shaco': ['Jungle', 'Sup'],
 'Shen': ['Top'],
 'Shyvana': ['Top', 'Jungle'],
 'Singed': ['Top'],
 'Sion': ['Top'],
 'Sivir': ['Bot'],
 'Skarner': ['Jungle'],
 'Sona': ['Sup'],
 'Soraka': ['Sup'],
 'Swain': ['Bot', 'Sup'],
 'Sylas': ['Jungle', 'Mid'],
 'Syndra': ['Mid'],
 'Tahm Kench': ['Top', 'Sup'],
 'Taliyah': ['Jungle', 'Mid'],
 'Talon': ['Jungle', 'Mid'],
 'Taric': ['Sup'],
 'Teemo': ['Top'],
 'Thresh': ['Sup'],
 'Tristana': ['Mid', 'Bot'],
 'Trundle': ['Top', 'Jungle'],
 'Tryndamere': ['Top'],
 'Twisted Fate': ['Mid'],
 'Twitch': ['Bot'],
 'Udyr': ['Top', 'Jungle'],
 'Urgot': ['Top'],
 'Varus': ['Bot'],
 'Vayne': ['Bot'],
 'Veigar': ['Mid'],
 "Vel'Koz": ['Mid', 'Sup'],
 'Vex': ['Mid'],
 'Vi': ['Jungle'],
 'Viego': ['Jungle'],
 'Viktor': ['Mid'],
 'Vladimir': ['Top', 'Mid'],
 'Volibear': ['Top'],
 'Warwick': ['Top', 'Jungle'],
 'Xayah': ['Bot'],
 'Xerath': ['Mid', 'Sup'],
 'Xin Zhao': ['Jungle'],
 'Yasuo': ['Mid'],
 'Yone': ['Top', 'Mid'],
 'Yorick': ['Top'],
 'Yuumi': ['Sup'],
 'Zac': ['Jungle'],
 'Zed': ['Mid'],
 'Zeri': ['Bot'],
 'Ziggs': ['Mid', 'Bot'],
 'Zilean': ['Bot'],
 'Zoe': ['Mid'],
 'Zyra': ['Sup']}

In [122]:
champ_role_dict['Alistar']

['Sup']

In [123]:
#Iterates through a dictionary (e.g account_list) to provide a dictionary total for all accounts in the list
def pro_dict_to_mastery(pros, role):
    percentage_dict = {}
    mastery_dict = {}
    mastery_dict['total'] = 0
    #iterates through reigon
    for region in list(pros.keys()): 
        rr = region.replace(':', '')
        #iterate through account name and makes a 
        for account in list(pros[region]):
            ss = ra.get_mastery_by_summoner_name(account, rr)
            for num in range(len(ss.get('championName'))):
                champ = ss.get('championName')[num+1]
                champ_points = ss.get('championPoints')[num+1]
                # If the champion has not been played in another account, add it directly to the dictionary
                # If it has been played, update the dictionary's points by adding the points for this acc
                if champ not in list(mastery_dict.keys()): 
                    mastery_dict[champ] = champ_points
                else: 
                    mastery_dict[champ] += champ_points
    mastery_dict['total'] = sum(list(mastery_dict.values()))
    onetrickscore = 0
    mainrolescore = 0
    percentage_dict['onetrickscore'] = onetrickscore
    # creates a new dictionary where each champion key corresponds to a list 
    # featuring mastery points as 1st value and % total mastery points as 2nd value
    for champ in list(mastery_dict.keys()):
        
        #Onetrickscore is calculated by mean square error of the percentage_mastery of that champ 
        # vs the "expected" average of playing all 165 champs equally
        if champ != 'total':
            onetrickscore += (100 * mastery_dict[champ]/mastery_dict['total'] - (100/165))**2
        #if the champ is played in the player's main role, add the mastery points to the mainrolescore, then divide at the end
            if role in champ_role_dict[champ]:
                mainrolescore += mastery_dict[champ]
    mainrolepercent = mainrolescore/mastery_dict['total']
    percentage_dict['onetrickscore'] = onetrickscore
    #returns a list featuring mainrolescore, onetrickscore, and total mastery points
    return [mainrolepercent, onetrickscore, mastery_dict['total']]

[0.1998597159182916, 484.0422222809763, 2328133]

In [136]:
joe = []
for num in range(len(df.get('Account_list'))):
    joe.append([0, 1, 2])
js = []
jos = []
joes = []
for j in joe:
    js.append(j[0])
    jos.append(j[1])
    joes.append(j[2])
df['big daddy'] = js
df['huge daddy'] = jos
df['mega daddy'] = joes
df.to_csv("test.csv")

In [138]:
#This goes through the entire pro dataframe and runs the function on each pro player and their role
# It then adds the mainrolescore, onetrickscore, and totalmastery to the dataframe
# This takes a while to run
# It also saves the dataframe to a csv file called pro_mastery.csv
# This is the final dataframe that we will use for the project
# 
list_of_all_pros = []
mainrolescore = []
onetrickscore = []
totalmastery = []
for num in range(len(df.get('Account_list'))) : 
    try: list_of_all_pros.append(pro_dict_to_mastery(df.get('Account_list')[num], df.get('Roles (LeaguePedia)')[num]))
    except: list_of_all_pros.append([0, 0, 0])
for pro in list_of_all_pros:
    mainrolescore.append(pro[0])
    onetrickscore.append(pro[1])
    totalmastery.append(pro[2])
df['mainrolescore'] = mainrolescore
df['onetrickscore'] = onetrickscore
df['totalmastery'] = totalmastery
df.to_csv("pro_mastery.csv")
df

,Region,Team,Official Summoner Name,ids,Roles (LeaguePedia),Roles (RCD),Account_list,0,big daddy,huge daddy,mega daddy,mainrolescore,onetrickscore,totalmastery
0,BR,FLUXO,Baldan,{},Top,NaN,{'BR:': ['Baldan']},0,0,1,2,0.199860,484.042222,2328133
1,BR,FLUXO,Forlin,{},Top,NaN,{'BR:': ['Forlin']},0,0,1,2,0.855939,600.442003,1010865
2,BR,FLUXO,Tay,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303...",Top,NaN,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303...",0,0,1,2,0.000000,0.000000,0
3,BR,FLUXO,Disamis,{},Jungle,NaN,{'BR:': ['Disamis']},0,0,1,2,0.543653,360.117354,396814
4,BR,FLUXO,Ancrath,{},Jungle,NaN,{'BR:': ['Ancrath']},0,0,1,2,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193,VN,NaN,Emo,{},Mid,Sub/Mid,{'VN:': ['Emo']},0,0,1,2,0.000000,0.000000,0
1194,VN,NaN,Nugu,"{'VN': '211221', 'KR': '우주를 줄게 1802'}",Mid,Mid,"{'VN': '211221', 'KR': '우주를 줄게 1802', 'VN:': [...",0,0,1,2,0.000000,0.000000,0
1195,VN,NaN,Slowz,{},Top,Bot,{'VN:': ['Slowz']},0,0,1,2,0.000000,0.000000,0
1196,VN,NaN,Zodiac,{'VN': ['Zodiac12']},Sup,Sup,"{'VN': ['Zodiac12'], 'VN:': ['Zodiac']}",0,0,1,2,0.000000,0.000000,0
1197,VN,NaN,Ryuk,{},Top,Sub/Top,{'VN:': ['Ryuk']},0,0,1,2,0.000000,0.000000,0

In [115]:
df

,Region,Team,Official Summoner Name,ids,Roles (LeaguePedia),Roles (RCD),Account_list
0,BR,FLUXO,Baldan,{},Top,NaN,{'BR:': ['Baldan']}
1,BR,FLUXO,Forlin,{},Top,NaN,{'BR:': ['Forlin']}
2,BR,FLUXO,Tay,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303...",Top,NaN,"{'None': ['BR: 7ay', 'Esdeath', 'FPXzhaoTOP303..."
3,BR,FLUXO,Disamis,{},Jungle,NaN,{'BR:': ['Disamis']}
4,BR,FLUXO,Ancrath,{},Jungle,NaN,{'BR:': ['Ancrath']}
...,...,...,...,...,...,...,...
1193,VN,NaN,Emo,{},Mid,Sub/Mid,{'VN:': ['Emo']}
1194,VN,NaN,Nugu,"{'VN': '211221', 'KR': '우주를 줄게 1802'}",Mid,Mid,"{'VN': '211221', 'KR': '우주를 줄게 1802', 'VN:': [..."
1195,VN,NaN,Slowz,{},Top,Bot,{'VN:': ['Slowz']}
1196,VN,NaN,Zodiac,{'VN': ['Zodiac12']},Sup,Sup,"{'VN': ['Zodiac12'], 'VN:': ['Zodiac']}"
1197,VN,NaN,Ryuk,{},Top,Sub/Top,{'VN:': ['Ryuk']}

In [80]:
for num in range (0,2) : 
    print(num)

0
1

In [41]:
df

,Region,Team,Official Summoner Name,Roles,Legal First Name,Legal Family Name,End Date,Scrapped Roles,Alts,Account_list
0,BR,FLUXO,Baldan,NaN,Giovani,Baldan,2024-11-18 00:00:00,Top Laner,{},{'BR:': ['Baldan']}
1,BR,FLUXO,Forlin,NaN,Leonardo,Pereira,2024-11-18 00:00:00,Top Laner,{},{'BR:': ['Forlin']}
2,BR,FLUXO,Tay,NaN,Rodrigo,Panisa,2023-11-20 00:00:00,Top Laner,"{'BR:': ['7ay', 'Esdeath', 'FPXzhaoTOP303485']...","{'BR:': ['7ay', 'Esdeath', 'FPXzhaoTOP303485',..."
3,BR,FLUXO,Disamis,NaN,Pedro,Cavalcante,2024-11-18 00:00:00,Jungler,{},{'BR:': ['Disamis']}
4,BR,FLUXO,Ancrath,NaN,Rodrigo,Montrezol,2024-11-18 00:00:00,Jungler,{},{'BR:': ['Ancrath']}
...,...,...,...,...,...,...,...,...,...,...
155,BR,Vivo Keyd Stars,Mitohara,NaN,Kenzo,Sampaio,2024-11-18 00:00:00,Coach,{},{'BR:': ['Mitohara']}
156,CN,XianTeamWE,Demon,Top,YUEWEI,WU,2024-11-19 00:00:00,Bot Laner,{},{'CN:': ['Demon']}
157,CN,XianTeamWE,Hope,Bot,JIE,WANG,2023-11-21 00:00:00,Mid Laner,{},{'CN:': ['Hope']}
158,CN,XianTeamWE,Iwandy,Sup,DINGYANG,LIAO,2023-11-21 00:00:00,Top Laner,{},{'CN:': ['Iwandy']}
159,CN,XianTeamWE,Shanks,Mid,XIAOJUN,CUI,2023-11-21 00:00:00,Support,{},{'CN:': ['Shanks']}

In [31]:
mastery_dict = {}
#creates a dictionary for each champion where the key is the champname and the
#value is the mastery points
for num in range(len(ts.get('championName'))):
    champ = ts.get('championName')[num+1]
    champ_points = ts.get('championPoints')[num+1]
    if champ not in list(mastery_dict.keys()): 
        mastery_dict[champ] = champ_points
#adds up to the total
mastery_dict['total'] = sum(list(mastery_dict.values()))
mastery_dict

{'Neeko': 130678,
 'Ezreal': 51703,
 'Ashe': 48314,
 'Swain': 44314,
 'Seraphine': 33838,
 'Varus': 33717,
 'Janna': 25932,
 'Rakan': 22275,
 'Karma': 18243,
 'Karthus': 15843,
 'Miss Fortune': 15118,
 'Caitlyn': 14543,
 'Sejuani': 13784,
 'Veigar': 12317,
 'Lux': 12283,
 'Leona': 9605,
 "Kai'Sa": 8683,
 'Nidalee': 8097,
 "Kog'Maw": 8081,
 'Soraka': 7115,
 'Senna': 6998,
 'Sivir': 6378,
 'Brand': 6015,
 'Sona': 5712,
 'Taliyah': 5588,
 'Renata Glasc': 4613,
 'Jhin': 4612,
 'Master Yi': 3973,
 'Jarvan IV': 3792,
 'Xerath': 3569,
 'Rumble': 3475,
 'Teemo': 3383,
 'Pantheon': 3377,
 'Lulu': 3232,
 'Anivia': 3048,
 'Diana': 2986,
 'Kayle': 2791,
 'Annie': 2740,
 'Maokai': 2494,
 'Twitch': 2488,
 'Rell': 2337,
 'Jinx': 2291,
 'Amumu': 2107,
 'Nunu & Willump': 2073,
 "Cho'Gath": 1975,
 'Morgana': 1903,
 'Fiddlesticks': 1883,
 'Braum': 1881,
 'Ziggs': 1822,
 'Shaco': 1804,
 'Syndra': 1781,
 'Elise': 1567,
 'Twisted Fate': 1559,
 'Taric': 1549,
 'Nami': 1541,
 'Blitzcrank': 1386,
 'Vi': 1331,
 'Yone': 1252,
 'Vladimir': 1210,
 'Xin Zhao': 1115,
 'Rammus': 1084,
 'Riven': 1064,
 'Zac': 1056,
 'Mordekaiser': 1033,
 'Akshan': 1006,
 'Malphite': 1004,
 'Irelia': 944,
 'Tryndamere': 937,
 "Bel'Veth": 909,
 'Tristana': 899,
 'Yuumi': 897,
 'Alistar': 895,
 "Kha'Zix": 847,
 'Dr. Mundo': 841,
 'Kassadin': 814,
 'Nautilus': 799,
 'Lillia': 741,
 'Xayah': 667,
 'Graves': 662,
 'LeBlanc': 627,
 'Heimerdinger': 625,
 'Samira': 600,
 'Akali': 553,
 'Aatrox': 363,
 'Garen': 303,
 'Ahri': 281,
 'Volibear': 271,
 'Pyke': 263,
 'Ryze': 235,
 'Zilean': 215,
 'Nasus': 200,
 'Aphelios': 199,
 'Ivern': 166,
 "K'Sante": 159,
 'Singed': 155,
 'Vex': 146,
 'Wukong': 133,
 'Thresh': 131,
 'Zyra': 131,
 'Zeri': 129,
 'Draven': 124,
 'Camille': 123,
 "Vel'Koz": 121,
 'Gangplank': 115,
 'Orianna': 101,
 'Yorick': 80,
 'total': 673762}

In [14]:
"""i could just add NA1 back to the regionDict if needed
it's in the class attributes for RA"""
ra